import type { Lang } from "@/app/languages";

const en = {
  back: "Back to website", title: "Complete your booking", subtitle: "Choose an available session and ticket category. Your tickets will be held for 15 minutes while you complete payment.",
  secureCheckout: "Secure booking", visitFacts: "Experience facts", bookingProcess: "Booking process",
  duration: "Experience", durationValue: "Approx. 110 min", location: "Location", locationValue: "Chongqing · Baguocheng", language: "Visitor support", languageValue: "English on request", bookingType: "Booking channel", bookingTypeValue: "Official direct booking",
  processDate: "Date & session", processTickets: "Tickets & guests", processDetails: "Contact details", processSeat: "Review & pay",
  date: "Visit date", session: "Choose a session", nextAvailable: "Next available", tickets: "Tickets", contact: "Guest details", payment: "Payment",
  sessionHelp: "Select your visit date first, then choose an available lunch or dinner session.", ticketHelp: "Choose the seating category and number of guests for your party.", contactHelp: "We use these details to send your confirmation and arrange your visit.",
  lunch: "Lunch", dinner: "Dinner", garden: "Garden", show: "Dinner show", remaining: "online tickets left",
  noShows: "No online sessions are published for this date. Please choose another date or contact the team.", loading: "Checking sessions...",
  name: "Lead guest name", email: "Confirmation email", phone: "Phone / WhatsApp", country: "Country / region", notes: "Dietary needs or notes",
  namePlaceholder: "Name as used for the booking", phonePlaceholder: "+1 202 555 0123", countryPlaceholder: "e.g. Singapore", notesPlaceholder: "Allergies, dietary needs, accessibility or celebration notes", primaryContactNote: "Enter one lead guest. Customer service will contact this person about seat numbers and visit details.",
  summary: "Order summary", total: "Total", empty: "No tickets selected", emptyHelp: "Choose a date, session and at least one ticket to continue.", create: "Continue to mock payment", creating: "Locking tickets...",
  notice: "Phase 1 acceptance mode: no real payment will be charged.", error: "We could not create the order. Please check availability and try again.",
  seatNoticeTitle: "Contact customer service after purchase to confirm your seat number",
  seatNotice: "Online tickets confirm the seating category and quantity. Exact seat numbers are arranged by customer service after payment based on party size and current availability.",
  seatSummary: "Exact seat numbers are confirmed with customer service after payment.",
};

export type CheckoutCopy = typeof en;

export const checkoutCopy: Record<Lang, CheckoutCopy> = {
  en,
  zh: {
    back: "返回官网", title: "完成您的礼宴预订", subtitle: "选择可预订场次与席位等级。订单创建后，票务库存将为您保留 15 分钟。",
    secureCheckout: "安全预订", visitFacts: "体验信息", bookingProcess: "预订流程",
    duration: "体验时长", durationValue: "餐秀约 110 分钟", location: "体验地点", locationValue: "重庆 · 巴国城", language: "游客支持", languageValue: "可预约英文接待", bookingType: "预订渠道", bookingTypeValue: "官方直营预订",
    processDate: "日期与场次", processTickets: "票种与人数", processDetails: "联系方式", processSeat: "确认并支付",
    date: "到访日期", session: "选择场次", nextAvailable: "近期可订", tickets: "选择票种", contact: "宾客信息", payment: "支付",
    sessionHelp: "先选择到访日期，再从当天可售的午宴或晚宴中选择场次。", ticketHelp: "按同行人数选择席位等级和数量，价格均为单人价格。", contactHelp: "用于接收订单确认，并由客服与您沟通座位和到访事项。",
    lunch: "午宴", dinner: "晚宴", garden: "游园活动", show: "餐秀表演", remaining: "张线上余票",
    noShows: "该日期暂未发布线上场次，请选择其他日期或联系客服。", loading: "正在查询场次...",
    name: "主要联系人姓名", email: "接收确认的邮箱", phone: "手机 / WhatsApp", country: "国家 / 地区", notes: "忌口、过敏或备注",
    namePlaceholder: "请填写主要联系人姓名", phonePlaceholder: "+86 138 0000 0000", countryPlaceholder: "例如：新加坡", notesPlaceholder: "可填写过敏、饮食、无障碍或庆祝需求", primaryContactNote: "仅需填写一位主要联系人。客服将通过该联系方式确认座位号与到访细节。",
    summary: "订单明细", total: "合计", empty: "尚未选择票种", emptyHelp: "选择日期、场次和票种后，订单信息将显示在这里。", create: "继续模拟支付", creating: "正在锁定席位...",
    notice: "一期验收模式：不会产生真实扣款。", error: "订单创建失败，请确认余票后重试。",
    seatNoticeTitle: "购买后需联系客服确认座位号",
    seatNotice: "线上购票确认席位等级和数量，不自动分配具体座位号。付款完成后，请凭订单号联系客服，客服将结合同行人数与现场余位安排座位。",
    seatSummary: "具体座位号将在付款后由客服与您确认。",
  },
  tw: {
    back: "返回官網", title: "完成您的禮宴預訂", subtitle: "選擇可預訂場次與席位等級。訂單建立後，票務庫存將保留 15 分鐘。",
    secureCheckout: "安全預訂", visitFacts: "體驗資訊", bookingProcess: "預訂流程",
    duration: "體驗時長", durationValue: "餐秀約 110 分鐘", location: "體驗地點", locationValue: "重慶 · 巴國城", language: "旅客服務", languageValue: "可預約英文接待", bookingType: "預訂渠道", bookingTypeValue: "官方直接預訂",
    processDate: "日期與場次", processTickets: "票種與人數", processDetails: "聯絡資料", processSeat: "確認並付款",
    date: "到訪日期", session: "選擇場次", nextAvailable: "近期可訂", tickets: "選擇票種", contact: "賓客資料", payment: "付款",
    sessionHelp: "先選擇到訪日期，再從當天可售的午宴或晚宴中選擇場次。", ticketHelp: "按同行人數選擇席位等級和數量，價格均為單人價格。", contactHelp: "用於接收訂單確認，並由客服與您溝通座位和到訪事項。",
    lunch: "午宴", dinner: "晚宴", garden: "遊園活動", show: "餐秀表演", remaining: "張線上餘票",
    noShows: "該日期暫未發布線上場次，請選擇其他日期或聯絡客服。", loading: "正在查詢場次...",
    name: "主要聯絡人姓名", email: "接收確認的電郵", phone: "手機 / WhatsApp", country: "國家 / 地區", notes: "飲食需求或備註",
    namePlaceholder: "請填寫主要聯絡人姓名", phonePlaceholder: "+852 9123 4567", countryPlaceholder: "例如：新加坡", notesPlaceholder: "可填寫過敏、飲食、無障礙或慶祝需求", primaryContactNote: "僅需填寫一位主要聯絡人。客服將透過此聯絡方式確認座位號與到訪細節。",
    summary: "訂單明細", total: "合計", empty: "尚未選擇票種", emptyHelp: "選擇日期、場次和票種後，訂單資料將顯示在這裡。", create: "繼續模擬付款", creating: "正在鎖定席位...",
    notice: "一期驗收模式：不會產生真實扣款。", error: "訂單建立失敗，請確認餘票後重試。",
    seatNoticeTitle: "購買後需聯絡客服確認座位號",
    seatNotice: "線上購票確認席位等級和數量，不會自動分配具體座位號。付款完成後，請憑訂單號聯絡客服安排座位。",
    seatSummary: "具體座位號將在付款後由客服與您確認。",
  },
  ja: {
    back: "公式サイトへ戻る", title: "予約を完了する", subtitle: "予約可能な公演と座席カテゴリーを選択してください。注文作成後、チケットは15分間確保されます。",
    secureCheckout: "安全な予約", visitFacts: "体験情報", bookingProcess: "予約の流れ",
    duration: "所要時間", durationValue: "ショー約110分", location: "場所", locationValue: "重慶・巴国城", language: "旅行者サポート", languageValue: "英語対応は要予約", bookingType: "予約方法", bookingTypeValue: "公式サイト直接予約",
    processDate: "日付・公演", processTickets: "チケット・人数", processDetails: "連絡先", processSeat: "確認・支払い",
    date: "来場日", session: "公演を選択", nextAvailable: "直近の予約可能日", tickets: "チケット", contact: "お客様情報", payment: "支払い",
    sessionHelp: "来場日を選び、その日に販売中の昼宴または夜宴を選択してください。", ticketHelp: "同行人数に合わせて座席カテゴリーと枚数を選択してください。表示価格は1名分です。", contactHelp: "予約確認の送信および座席・来場案内のご連絡に使用します。",
    lunch: "昼宴", dinner: "夜宴", garden: "庭園体験", show: "ディナーショー", remaining: "枚のオンライン残席",
    noShows: "この日はオンライン公演が公開されていません。別の日を選ぶか、お問い合わせください。", loading: "公演を確認中...",
    name: "代表者名", email: "確認メール送信先", phone: "電話 / WhatsApp", country: "国・地域", notes: "食事制限・備考",
    namePlaceholder: "予約代表者のお名前", phonePlaceholder: "+81 90 1234 5678", countryPlaceholder: "例：日本", notesPlaceholder: "アレルギー、食事、アクセシビリティ、記念日のご希望", primaryContactNote: "代表者1名の情報をご入力ください。座席番号と来場詳細はカスタマーサービスからご連絡します。",
    summary: "注文内容", total: "合計", empty: "チケットが選択されていません", emptyHelp: "日付、公演、チケットを選ぶと、ここに注文内容が表示されます。", create: "テスト決済へ進む", creating: "座席を確保中...",
    notice: "フェーズ1検収モード：実際の請求は発生しません。", error: "注文を作成できませんでした。残席を確認して再試行してください。",
    seatNoticeTitle: "購入後、カスタマーサービスに座席番号をご確認ください",
    seatNotice: "オンラインチケットでは座席カテゴリーと枚数が確定します。具体的な座席番号は、支払い後に注文番号を添えてカスタマーサービスへご連絡ください。",
    seatSummary: "具体的な座席番号は、お支払い後にカスタマーサービスが確認します。",
  },
  ko: {
    back: "공식 사이트로 돌아가기", title: "예약 완료하기", subtitle: "예약 가능한 회차와 좌석 등급을 선택하세요. 주문 생성 후 티켓은 15분 동안 보류됩니다.",
    secureCheckout: "안전한 예약", visitFacts: "체험 정보", bookingProcess: "예약 절차",
    duration: "소요 시간", durationValue: "공연 약 110분", location: "장소", locationValue: "충칭·바궈청", language: "여행객 지원", languageValue: "영어 지원 사전 요청", bookingType: "예약 채널", bookingTypeValue: "공식 직접 예약",
    processDate: "날짜·회차", processTickets: "티켓·인원", processDetails: "연락처", processSeat: "확인·결제",
    date: "방문일", session: "회차 선택", nextAvailable: "가까운 예약 가능일", tickets: "티켓", contact: "방문객 정보", payment: "결제",
    sessionHelp: "방문일을 먼저 선택한 뒤 해당 날짜에 판매 중인 오찬 또는 만찬 회차를 선택하세요.", ticketHelp: "동행 인원에 맞춰 좌석 등급과 수량을 선택하세요. 표시 가격은 1인 기준입니다.", contactHelp: "예약 확인 전송과 좌석 및 방문 안내 연락에 사용됩니다.",
    lunch: "오찬", dinner: "만찬", garden: "정원 체험", show: "디너쇼", remaining: "장 온라인 잔여",
    noShows: "이 날짜에는 공개된 온라인 회차가 없습니다. 다른 날짜를 선택하거나 문의해 주세요.", loading: "회차 확인 중...",
    name: "대표 예약자 이름", email: "확인 이메일", phone: "전화 / WhatsApp", country: "국가 / 지역", notes: "식이 요청 또는 메모",
    namePlaceholder: "대표 예약자 이름", phonePlaceholder: "+82 10 1234 5678", countryPlaceholder: "예: 대한민국", notesPlaceholder: "알레르기, 식이, 접근성 또는 기념일 요청", primaryContactNote: "대표 연락처 한 명만 입력해 주세요. 고객센터에서 좌석 번호와 방문 세부 정보를 안내합니다.",
    summary: "주문 요약", total: "합계", empty: "선택한 티켓이 없습니다", emptyHelp: "날짜, 회차, 티켓을 선택하면 주문 정보가 여기에 표시됩니다.", create: "테스트 결제로 계속", creating: "좌석 확보 중...",
    notice: "1단계 검수 모드: 실제 결제는 발생하지 않습니다.", error: "주문을 만들 수 없습니다. 잔여 좌석을 확인하고 다시 시도하세요.",
    seatNoticeTitle: "구매 후 고객센터에 좌석 번호를 확인해 주세요",
    seatNotice: "온라인 티켓은 좌석 등급과 수량을 확정합니다. 정확한 좌석 번호는 결제 후 주문 번호와 함께 고객센터에 문의해 배정받으세요.",
    seatSummary: "정확한 좌석 번호는 결제 후 고객센터에서 확인합니다.",
  },
};
