import Image from "next/image";
import Link from "next/link";
import type { Metadata } from "next";
import { languages, type Lang } from "../../languages";
import { siteSeo, getCanonicalPath, getHreflang } from "../../seo";
import { InnerPageShell, DetailFaq } from "../InnerPageShell";
import { CopyButton } from "../CopyButton";

export function generateStaticParams() { return languages.map((lang) => ({ lang })); }
export async function generateMetadata({ params }: { params: Promise<{ lang: Lang }> }): Promise<Metadata> { const { lang } = await params; const seo = siteSeo[lang].location; return { title: seo.title, description: seo.description, alternates: { canonical: getCanonicalPath(lang, "location-booking"), languages: getHreflang("location-booking") } }; }

const zhAddress = "中国重庆市九龙坡区巴国城";
const enAddress = "Baguocheng, Jiulongpo District, Chongqing, China";

export default async function Page({ params }: { params: Promise<{ lang: Lang }> }) {
  const { lang } = await params; const en = lang === "en";
  return <InnerPageShell lang={lang} eyebrow="LOCATION & BOOKING" title={en ? "Plan Your Visit" : "地址、交通与预订"} summary={en ? "Save the address, open your preferred map and confirm the session before setting out." : "保存中英文地址、打开常用地图，并在出发前确认场次。"} image="/images/gallery-sea-1.webp">
    <section className="inner-section location-lead"><div className="address-panel"><p className="eyebrow">VENUE ADDRESS</p><h2>{en ? "Ba Kingdom City, Chongqing" : "重庆 · 巴国城"}</h2><div className="address-line"><span>{en ? "Chinese" : "中文地址"}</span><strong>{zhAddress}</strong><CopyButton value={zhAddress} label={en ? "Copy Chinese address" : "复制中文地址"} copiedLabel={en ? "Copied" : "已复制"} /></div><div className="address-line"><span>{en ? "English" : "英文地址"}</span><strong>{enAddress}</strong><CopyButton value={enAddress} label={en ? "Copy English address" : "复制英文地址"} copiedLabel={en ? "Copied" : "已复制"} /></div><div className="venue-hours"><span>{en ? "Opening hours" : "营业时间"}</span><strong>{en ? "Daily 10:00–21:00" : "每日 10:00–21:00"}</strong></div></div><figure><Image src="/images/gallery-sea-4.webp" alt={en ? "Ba Kingdom Banquet venue entrance" : "礼宴巴国场地入口"} fill sizes="(max-width:800px) 92vw,44vw" /></figure></section>
    <section className="inner-section map-section"><p className="eyebrow">MAP & NAVIGATION</p><h2>{en ? "Open the route in one tap" : "一键打开导航路线"}</h2><div className="map-embed"><iframe title={en ? "Map of Baguocheng Chongqing" : "重庆巴国城地图"} src="https://www.google.com/maps?q=%E9%87%8D%E5%BA%86%E5%B7%B4%E5%9B%BD%E5%9F%8E&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /></div><div className="map-actions refined"><a href="https://j.map.baidu.com/76/_1tc" target="_blank" rel="noreferrer">百度地图</a><a href="https://uri.amap.com/search?keyword=%E5%B7%B4%E5%9B%BD%E5%9F%8E&city=%E9%87%8D%E5%BA%86" target="_blank" rel="noreferrer">高德地图</a><a href="https://maps.app.goo.gl/ZddotMySGkJYsjFh7" target="_blank" rel="noreferrer">Google Maps</a></div></section>
    <section className="inner-section arrival-grid"><p className="eyebrow">GETTING HERE</p><h2>{en ? "Choose the most convenient arrival" : "选择适合你的到达方式"}</h2><div><article><span aria-hidden="true">轨</span><h3>{en ? "Metro & public transport" : "地铁与公共交通"}</h3><p>{en ? "Use your map app for the current route to Baguocheng. Follow the live station and exit guidance shown on the day." : "请使用地图应用实时规划至“巴国城”，地铁线路和出口以出发当天导航为准。"}</p></article><article><span aria-hidden="true">车</span><h3>{en ? "Taxi / Ride-hailing" : "出租车 / 网约车"}</h3><p>{en ? "Enter “巴国城” and compare the destination with the Chinese address above before departure." : "搜索“巴国城”，出发前与页面中文地址核对目的地。"}</p></article><article><span aria-hidden="true">停</span><h3>{en ? "Driving & parking" : "自驾与停车"}</h3><p>{en ? "Navigate to Baguocheng and confirm the available parking entrance with the venue before arrival." : "导航至巴国城；停车入口和当日车位请在到场前联系确认。"}</p></article></div></section>
    <section className="inner-section contact-cards"><p className="eyebrow">CONTACT</p><h2>{en ? "Contact and booking" : "联系与预约"}</h2><div><a href="tel:+8617383017612"><small>{en ? "Phone" : "电话 · 点击拨号"}</small><strong>+86 173 8301 7612</strong></a><a href="mailto:liaorenxi23@gmail.com"><small>Email</small><strong>liaorenxi23@gmail.com</strong></a><article><small>WeChat</small><strong>cqlybg8866</strong><CopyButton value="cqlybg8866" label={en ? "Copy WeChat" : "复制微信号"} copiedLabel={en ? "Copied" : "已复制"} /></article></div><Link className="button" href={`/${lang}/#booking`}>{en ? "Open booking form" : "打开预订表单"}</Link></section>
    <DetailFaq title={en ? "Arrival questions" : "到访常见问题"} items={en ? [["When should I arrive?", "Arrive before the garden visit time shown for your session."], ["Which map can I use?", "Direct Baidu Maps, Amap and Google Maps links are provided above."], ["Where should a driver navigate?", "Use the Chinese name “巴国城” and verify the full address before departure."]] : [["应该提前多久到？", "请在所选场次的游园时间前抵达。"], ["可以使用哪些地图？", "页面提供百度地图、高德地图和 Google Maps 入口。"], ["司机应该导航到哪里？", "搜索“巴国城”，并在出发前核对页面完整中文地址。"]]} />
  </InnerPageShell>;
}
